[package]
name = "aocsuite-tui"
version = "0.4.1"
edition = "2021"

[dependencies]
aocsuite-client = { version = "0.4.1", path = "../aocsuite-client" }
aocsuite-config = { version = "0.4.1", path = "../aocsuite-config" }
aocsuite-lang = { version = "0.4.1", path = "../aocsuite-lang" }
aocsuite-launcher = { version = "0.4.1", path = "../aocsuite-launcher" }
aocsuite-parser = { version = "0.4.1", path = "../aocsuite-parser" }
aocsuite-storage = { version = "0.4.1", path = "../aocsuite-storage" }
aocsuite-utils = { version = "0.4.1", path = "../aocsuite-utils" }
crossterm.workspace = true
ratatui.workspace = true
thiserror.workspace = true
