[package]
name = "aocsuite-config"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
