[package]
name = "aocsuite-utils"
version = "0.2.0"
edition = "2024"

[dependencies]
chrono.workspace = true
chrono-tz.workspace = true
clap = { workspace=true, features = ["derive"] }
thiserror.workspace = true
