[package]
name = "aocsuite-storage"
version = "0.3.0"
edition = "2021"

[dependencies]
aocsuite-client = { version = "0.3.0", path = "../aocsuite-client" }
aocsuite-parser = { version = "0.3.0", path = "../aocsuite-parser" }
aocsuite-utils = { version = "0.3.0", path = "../aocsuite-utils" }
rusqlite.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile = "3.20.0"
